### ISSUE TITLE
Need Assistance with Large Dataset Merging

### ISSUE THREAD

**Issue by Leitemfa** [sgstepaniants/GromovMatcher#1]
Hello GromovMatcher team,

First of all, thank you very much for developing such wonderful approach. I am currently using the GromovMatcher algorithm for matching pairs of LC-MS untargeted metabolomic datasets, and I have encountered a couple of challenges for which I could use some guidance.

**Large Dataset Merging:**
I attempted to merge two very large datasets, each containing more than 60,000 features. Unfortunately, the process was terminated due to the lack of memory even when I run it in my university server, and I couldn't proceed. When I worked with a subset of the data, everything worked well. I am reaching out to seek advice on how to handle such large datasets successfully. Are there any recommended strategies or parameters that can help optimize the process for larger datasets?

**Feature Overlapping Analysis:**
Additionally, I am interested in using GromovMatcher to find overlapping metabolic features from different methods, specifically from a C18 column and a HILIC for the same set of samples. Can you provide insights into whether the GromovMatcher approach is suitable for identifying similar features from distinct analytical methods? If so, are there any specific considerations or parameters I should be aware of?

Thank you for your time and for developing this valuable tool. I appreciate any guidance or suggestions you can provide.

Marcio

**Comment by BreeurM** [comment]
Hi Marcio,

Concerning extensive datasets like yours, it seems you're exploring uncharted territories. We haven't yet tested GromovMatcher on datasets of such magnitude due to the substantial resource requirements involved. GromovMatcher handles matrices with a size proportional to the square of the number of features for Gromov-Wasserstein distance computation, making it quite considerable.
Our recommendation is to consider binning the data based on m/z values. GromovMatcher will not match features with significantly different m/z values, so we propose dividing the data into sets with similar m/z ranges. By doing so, you can then run GromovMatcher specifically on datasets that are m/z compatible. Alternatively, you could consider filtering your data or reducing the dimensionality.

Regarding your second point, this is an interesting question. The initial factor to ponder is the coverage of your analytical methods. If their expected disparities are substantial, the data overlap may be too low for GromovMatcher to operate efficiently. Conversely, if the methods have similar coverages, we anticipate that GromovMatcher should perform rather well. Nevertheless, it's worth noting that GromovMatcher won't capitalize on the fact that the samples are identical.
You might find it worthwhile to explore [this paper](https://pubs.acs.org/doi/pdf/10.1021/ac302227c) for comparison.

Thank you for using GromovMatcher, I hope those suggestions were helpful!

Marie
